### ISSUE TITLE
App crashes when clicking on the presets button

### ISSUE THREAD

**Issue by michelchafouin** [StudioPetrikas/Saulala#10]
Samsung S20 FE 5G - Android 13 - One UI 5.1
Saulala 0.2.9.0

100% reproducible: I press the second top button, I can see the Presets menu appear and then the app crashes. Not sure how I can provide a crash log.

**Comment by StudioPetrikas** [comment]
Hey, thanks for opening an issue. 
I can reproduce it on my end, will fix ASAP. Thanks again!

**Comment by StudioPetrikas** [comment]
Fixed in v0.2.10.0
