### ISSUE TITLE
Windows: Settings do not reset when importing a new image

### ISSUE THREAD

**Issue by Thane5** [StudioPetrikas/Saulala#13]
When i import a new image into the windows app, my previous edits persist. This is somehwat hindering my editing process, as i would like to start with the everything at the defaults.

Is there a way to quickly reset everything?

**Comment by ThomasWilshaw** [comment]
Triple clicking a slider should reset them all.

**Comment by Thane5** [comment]
Can i also reset my crop settings?

**Comment by StudioPetrikas** [comment]
Crop settings should reset with every new image. Is that not the case?
Temporary workaround if a peoblem arises is to resize the window, that will force-reset crop.

**Comment by Thane5** [comment]
Yeah, the crop settings do reset for every new image. I was just wondering if there was a similar reset feature as with the double-click to reset sliders (which i also only now discovered).
