### ISSUE TITLE
Images are clipped despite being RAW, exposure doesn't recover highlight detail

### ISSUE THREAD

**Issue by vfxninjaeditor** [StudioPetrikas/Saulala#14]
I can provide a DNG file if needed, but as described the image was properly exposed (testing in Lightroom the exposure slider fully recovers details in the clouds and sky in my image). In Saulala the highlights are clipped and the exposure slider does not recover them.

Saulala -3.6 exposure
![image](https://github.com/user-attachments/assets/e3d3d78f-8171-41eb-a5f8-9743c7fe10f0)

Lightroom -3.6 exposure
![image](https://github.com/user-attachments/assets/8ffa5af3-48a1-40eb-8856-1881cbf37aaf)

**Comment by StudioPetrikas** [comment]
Hi, thanks for the bug report.
Can you please tell me what version of Saulala you are running? Mobile or PC?
I'd be very curious to see the .dng that should not be happening.
Thanks!

**Comment by vfxninjaeditor** [comment]
I just tested the new version. Results seem to be a lot better!

**Comment by StudioPetrikas** [comment]
Reverted from 'clip' to 'blend' in v0.8.4.7-beta
