### ISSUE TITLE
Stitched panoramas from Adobe Lightroom are not compatible

### ISSUE THREAD

**Issue by vfxninjaeditor** [StudioPetrikas/Saulala#15]
When I stitch a bunch of RAW images in Lightroom to create a pano the resulting DNG file will not import into Saulala

**Comment by StudioPetrikas** [comment]
Yes, only bayered .DNGs (think RAWs from cameras) are supported. Stitching a panorama in Lightroom develops the image and it no longer is 'RAW'. You could try exporting .EXR from Lightroom and loading that in. Make sure the colour settings are 'Linear' with REC.709 primaries.
