### ISSUE TITLE
Scrolling through the settings with a mouse pad causes the image to zoom in and out

### ISSUE THREAD

**Issue by vfxninjaeditor** [StudioPetrikas/Saulala#21]
This occurs using my Macbook.

**Comment by StudioPetrikas** [comment]
Uff, thanks. I have not realized that people scroll through the developer sliders. I always clicked-and-dragged. Rather embarrassing this one.

**Comment by StudioPetrikas** [comment]
Fixed in v0.8.9.8-beta.
