### ISSUE TITLE
DNG files taken with Halide on iOS don’t open anymore in v0.8.9.8-beta

### ISSUE THREAD

**Issue by vfxninjaeditor** [StudioPetrikas/Saulala#25]
I use Halide on my iPhone and before this new version of Saulala the DNG files it captured worked fine. Curious what changed? Hoping there’s a solution since this app really takes those iPhone shots to another level.

**Comment by StudioPetrikas** [comment]
Can you send me an example?

**Comment by vfxninjaeditor** [comment]
Here you go!
https://drive.proton.me/urls/Z751TBJ6MR#ZNKM3sAueS2i

**Comment by StudioPetrikas** [comment]
Thanks!

I've introduced lens curvature correction v0.8.9.8 for supported curvature instructions. Since not all instructions are supported, there will be a few file-loading-bugs, and the only way to catch them all is try different .dng files. 

Fixed in the next beta.

**Comment by vfxninjaeditor** [comment]
Excellent! Thanks for addressing it so quickly!

**Comment by StudioPetrikas** [comment]
Fixed in v0.9.0.4-beta
