### ISSUE TITLE
Android version <13

### ISSUE THREAD

**Issue by TheSirC** [StudioPetrikas/Saulala#3]
Is it planned to have the app available for previous versions of Android ?
Are there any API that are only present in Android 13 ?

**Comment by StudioPetrikas** [comment]
Sadly not.

From Google:
"Starting August 31, 2023:
New apps must target Android 13 (API level 33) or higher; except for Wear OS apps, which must target Android 11 (API level 30) or up to Android 13 (API level 33)."

**Comment by TheSirC** [comment]
Great. Google again... Sad to see the e-waste motto... 
Thanks for the reply and for your work !

**Comment by rodlie** [comment]
`Target` and `Min` SDK are two different things.

**Comment by StudioPetrikas** [comment]
> `Target` and `Min` SDK are two different things.

I'm not building this with conventional methods, so I need to use what works for me. 
Sadly, the lowest SDK that works with the features I have is 33.

**Comment by rodlie** [comment]
Ok, thanks for the feedback (btw this issue is pinned while closed, why I noticed it).
