### ISSUE TITLE
[Feature]: Register Saulala as a RAW editor

### ISSUE THREAD

**Issue by benthillerkus** [StudioPetrikas/Saulala#9]
I have to admit, I don't know how exactly this works, but there seems to be some way to register an app as being a RAW editor on Android. Maybe it has to support a specific intent? Either way, if it does, gallery apps will offer you to edit dng files in that app
![image](https://github.com/StudioPetrikas/Saulala/assets/29630575/4a7a531d-3ae2-48ad-bebe-751e3317b6cd)

**Comment by StudioPetrikas** [comment]
Feature added in v0.4.2.2, thanks for the suggestion.
